apiVersion: v1
kind: Service
metadata:
  name: ${project.artifactId}
  labels:
    app: ${project.artifactId}
spec:
  type: NodePort
  ports:
    - name: app
      port: 8080
      nodePort: 30000
    - name: actuator
      port: 8050
      nodePort: 30001
    - name: wiremock-http
      port: 8090
      nodePort: 30090
    - name: wiremock-https
      port: 8443
      nodePort: 30093
  selector:
    app: ${project.artifactId}
